import os
import zipfile
import tempfile
import shutil
from datetime import datetime
from jinja2 import Template
import json
import base64

class PortfolioGenerator:
    def __init__(self):
        self.templates_dir = os.path.join(os.path.dirname(__file__), 'templates')
        if not os.path.exists(self.templates_dir):
            os.makedirs(self.templates_dir)
    
    def generate_portfolio_zip(self, portfolio_data, template_name='modern'):
        """Generate a complete portfolio website as a zip file"""
        
        # Create temporary directory
        with tempfile.TemporaryDirectory() as temp_dir:
            portfolio_dir = os.path.join(temp_dir, 'portfolio')
            os.makedirs(portfolio_dir)
            
            # Generate HTML file
            html_content = self._generate_html(portfolio_data, template_name)
            with open(os.path.join(portfolio_dir, 'index.html'), 'w', encoding='utf-8') as f:
                f.write(html_content)
            
            # Generate CSS file
            css_content = self._generate_css(template_name)
            with open(os.path.join(portfolio_dir, 'styles.css'), 'w', encoding='utf-8') as f:
                f.write(css_content)
            
            # Generate JavaScript file
            js_content = self._generate_js()
            with open(os.path.join(portfolio_dir, 'script.js'), 'w', encoding='utf-8') as f:
                f.write(js_content)
            
            # Create README file
            readme_content = self._generate_readme(portfolio_data)
            with open(os.path.join(portfolio_dir, 'README.md'), 'w', encoding='utf-8') as f:
                f.write(readme_content)
            
            # Create attribution notice
            attribution_content = self._generate_attribution_notice(portfolio_data)
            with open(os.path.join(portfolio_dir, 'ATTRIBUTION_NOTICE.txt'), 'w', encoding='utf-8') as f:
                f.write(attribution_content)
            
            # Create zip file
            zip_path = os.path.join(temp_dir, f"portfolio_{datetime.now().strftime('%Y%m%d_%H%M%S')}.zip")
            with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
                for root, dirs, files in os.walk(portfolio_dir):
                    for file in files:
                        file_path = os.path.join(root, file)
                        arcname = os.path.relpath(file_path, portfolio_dir)
                        zipf.write(file_path, arcname)
            
            # Read zip file content
            with open(zip_path, 'rb') as f:
                zip_content = f.read()
            
            return zip_content
    
    def _generate_html(self, portfolio_data, template_name):
        """Generate HTML content with unremovable watermark"""
        
        # AutoPortfolio watermark (encoded to make it harder to remove)
        watermark_data = base64.b64encode(b"Generated by AutoPortfolio").decode()
        
        html_template = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ name }} - Portfolio</title>
    <link rel="stylesheet" href="styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <!-- AutoPortfolio Attribution (DO NOT REMOVE) -->
    <meta name="generator" content="AutoPortfolio - Intelligent Portfolio Generator">
    <meta name="autoportfolio-watermark" content="{{ watermark }}">
    <link rel="icon" type="image/svg+xml" href="data:image/svg+xml;base64,PHN2ZyB2aWV3Qm94PSIwIDAgNDggNDgiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJmYXZpY29uR3JhZGllbnQiIHgxPSIwJSIgeTE9IjAlIiB4Mj0iMTAwJSIgeTI9IjEwMCUiPjxzdG9wIG9mZnNldD0iMCUiIHN0b3AtY29sb3I9IiM2MzY2ZjEiLz48c3RvcCBvZmZzZXQ9IjUwJSIgc3RvcC1jb2xvcj0iIzhiNWNmNiIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzA2YjZkNCIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxjaXJjbGUgY3g9IjI0IiBjeT0iMjQiIHI9IjIyIiBmaWxsPSJ1cmwoI2Zhdmljb25HcmFkaWVudCkiLz48ZyBmaWxsPSJ3aGl0ZSIgZmlsbC1vcGFjaXR5PSIwLjk1Ij48cmVjdCB4PSIxOCIgeT0iMTYiIHdpZHRoPSIxMiIgaGVpZ2h0PSI4IiByeD0iMiIvPjxjaXJjbGUgY3g9IjIwIiBjeT0iMTkiIHI9IjEuNSIvPjxjaXJjbGUgY3g9IjI4IiBjeT0iMTkiIHI9IjEuNSIvPjxyZWN0IHg9IjIxIiB5PSIyMSIgd2lkdGg9IjYiIGhlaWdodD0iMSIgcng9IjAuNSIvPjxwYXRoIGQ9Ik0xMiAyNGg0bTE2IDBoNE0yNCAxMnY0bTAgMTZ2NCIgc3Ryb2tlPSJ3aGl0ZSIgc3Ryb2tlLXdpZHRoPSIyIiBzdHJva2Utb3BhY2l0eT0iMC42IiBmaWxsPSJub25lIi8+PHBhdGggZD0iTTE2IDE2bDIgMm0xMi0ybC0yIDJNMTYgMzJsMi0ybTEyIDJsLTItMiIgc3Ryb2tlPSJ3aGl0ZSIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1vcGFjaXR5PSIwLjQiIGZpbGw9Im5vbmUiLz48Y2lyY2xlIGN4PSIxMiIgY3k9IjI0IiByPSIyIiBmaWxsLW9wYWNpdHk9IjAuNyIvPjxjaXJjbGUgY3g9IjM2IiBjeT0iMjQiIHI9IjIiIGZpbGwtb3BhY2l0eT0iMC43Ii8+PGNpcmNsZSBjeD0iMjQiIGN5PSIxMiIgcj0iMiIgZmlsbC1vcGFjaXR5PSIwLjciLz48Y2lyY2xlIGN4PSIyNCIgY3k9IjM2IiByPSIyIiBmaWxsLW9wYWNpdHk9IjAuNyIvPjwvZz48L3N2Zz4K">
</head>
<body class="{{ template_name }}-theme">
    <!-- AutoPortfolio Watermark (Protected) -->
    <div id="ap-watermark" class="ap-watermark" data-ap="{{ watermark }}">
        <a href="https://github.com/v-vekpawar/autoportfolio" target="_blank" rel="noopener">
            <i class="fas fa-robot"></i> Built with AutoPortfolio
        </a>
    </div>

    <!-- Header -->
    <header class="header">
        <nav class="nav">
            <div class="nav-brand">{{ name }}</div>
            <ul class="nav-menu">
                <li><a href="#about">About</a></li>
                <li><a href="#experience">Experience</a></li>
                <li><a href="#projects">Projects</a></li>
                <li><a href="#skills">Skills</a></li>
                {% if education %}<li><a href="#education">Education</a></li>{% endif %}
                <li><a href="#contact">Contact</a></li>
            </ul>
        </nav>
    </header>

    <!-- Hero Section -->
    <section id="hero" class="hero">
        <div class="container">
            <div class="hero-content">
                <h1 class="hero-title">{{ name }}</h1>
                <p class="hero-subtitle">{{ headline }}</p>
                <p class="hero-description">{{ about }}</p>
                <div class="hero-buttons">
                    <a href="#contact" class="btn btn-primary">Get In Touch</a>
                    <a href="#projects" class="btn btn-secondary">View Projects</a>
                </div>
            </div>
        </div>
    </section>

    <!-- Experience Section -->
    {% if experience %}
    <section id="experience" class="section">
        <div class="container">
            <h2 class="section-title">Experience</h2>
            <div class="timeline">
                {% for exp in experience %}
                <div class="timeline-item">
                    <div class="timeline-content">
                        <h3>{{ exp.title }}</h3>
                        <h4>{{ exp.company }}</h4>
                        <span class="timeline-date">{{ exp.duration }}</span>
                        <p>{{ exp.description }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endif %}

    <!-- Projects Section -->
    {% if projects %}
    <section id="projects" class="section">
        <div class="container">
            <h2 class="section-title">Projects</h2>
            <div class="projects-grid">
                {% for project in projects %}
                <div class="project-card">
                    <h3>{{ project.name }}</h3>
                    <p>{{ project.description }}</p>
                    {% if project.technologies %}
                    <div class="project-tech">
                        {% for tech in project.technologies %}
                        <span class="tech-tag">{{ tech }}</span>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div class="project-links">
                        {% if project.link %}<a href="{{ project.link }}" target="_blank" class="btn btn-sm">Live Demo</a>{% endif %}
                        {% if project.github %}<a href="{{ project.github }}" target="_blank" class="btn btn-sm btn-outline">GitHub</a>{% endif %}
                    </div>
                    {% if project.stars %}
                    <div class="project-stats">
                        <span><i class="fas fa-star"></i> {{ project.stars }}</span>
                    </div>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endif %}

    <!-- Skills Section -->
    {% if skills %}
    <section id="skills" class="section">
        <div class="container">
            <h2 class="section-title">Skills</h2>
            <div class="skills-grid">
                {% for skill in skills %}
                <div class="skill-item">{{ skill }}</div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endif %}

    <!-- Education Section -->
    {% if education %}
    <section id="education" class="section">
        <div class="container">
            <h2 class="section-title">Education</h2>
            <div class="education-list">
                {% for edu in education %}
                <div class="education-item">
                    <h3>{{ edu.degree }}</h3>
                    <h4>{{ edu.school or edu.institution }}</h4>
                    {% if edu.field %}<p>{{ edu.field }}</p>{% endif %}
                    {% if edu.year %}<span class="education-year">{{ edu.year }}</span>{% endif %}
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endif %}

    <!-- Certificates Section -->
    {% if certificates %}
    <section id="certificates" class="section">
        <div class="container">
            <h2 class="section-title">Certificates</h2>
            <div class="certificates-grid">
                {% for cert in certificates %}
                <div class="certificate-item">
                    <h3>{{ cert.certificate }}</h3>
                    <p>{{ cert.issuer }}</p>
                    {% if cert.date %}<span class="cert-date">{{ cert.date }}</span>{% endif %}
                    {% if cert.link %}<a href="{{ cert.link }}" target="_blank" class="btn btn-sm">View Certificate</a>{% endif %}
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endif %}

    <!-- Contact Section -->
    <section id="contact" class="section">
        <div class="container">
            <h2 class="section-title">Get In Touch</h2>
            <div class="contact-content">
                <p>Let's connect and discuss opportunities!</p>
                {% if contact %}
                <div class="contact-info">
                    {% if contact.email %}<a href="mailto:{{ contact.email }}" class="contact-link"><i class="fas fa-envelope"></i> {{ contact.email }}</a>{% endif %}
                    {% if contact.phone %}<a href="tel:{{ contact.phone }}" class="contact-link"><i class="fas fa-phone"></i> {{ contact.phone }}</a>{% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    </section>

    <!-- Footer with AutoPortfolio Attribution -->
    <footer class="footer">
        <div class="container">
            <p>&copy; {{ current_year }} {{ name }}. All rights reserved.</p>
            <div class="footer-attribution">
                <a href="https://github.com/v-vekpawar/autoportfolio" target="_blank" rel="noopener" class="ap-attribution">
                    <i class="fas fa-robot"></i> Generated by AutoPortfolio
                </a>
            </div>
        </div>
    </footer>

    <script src="script.js"></script>
</body>
</html>"""
        
        template = Template(html_template)
        return template.render(
            **portfolio_data,
            template_name=template_name,
            watermark=watermark_data,
            current_year=datetime.now().year
        )
    
    def _generate_css(self, template_name):
        """Generate CSS with protected watermark styles"""
        
        base_css = """
/* AutoPortfolio Generated Styles - DO NOT REMOVE ATTRIBUTION */
/* Generated by AutoPortfolio - https://github.com/v-vekpawar/autoportfolio */

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Inter', sans-serif;
    line-height: 1.6;
    color: var(--text-color);
    background-color: var(--bg-color);
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 20px;
}

/* AutoPortfolio Watermark Styles (PROTECTED - DO NOT REMOVE) */
/* License: Custom Proprietary License - Attribution Required */
.ap-watermark {
    position: fixed !important;
    bottom: 20px !important;
    right: 20px !important;
    z-index: 999999 !important;
    background: rgba(0, 0, 0, 0.85) !important;
    color: white !important;
    padding: 8px 12px !important;
    border-radius: 20px !important;
    font-size: 12px !important;
    backdrop-filter: blur(10px) !important;
    border: 1px solid rgba(255, 255, 255, 0.2) !important;
    transition: all 0.3s ease !important;
    display: block !important;
    visibility: visible !important;
    opacity: 1 !important;
    pointer-events: auto !important;
    user-select: none !important;
    -webkit-user-select: none !important;
    -moz-user-select: none !important;
    -ms-user-select: none !important;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif !important;
}

.ap-watermark:hover {
    background: rgba(0, 0, 0, 0.95) !important;
    transform: scale(1.05) !important;
    box-shadow: 0 8px 25px rgba(0, 0, 0, 0.3) !important;
}

.ap-watermark a {
    color: white !important;
    text-decoration: none !important;
    display: flex !important;
    align-items: center !important;
    gap: 5px !important;
}

.ap-watermark a:hover {
    color: white !important;
    text-decoration: none !important;
}

.ap-watermark i {
    color: #00d4ff !important;
    font-size: 14px !important;
}

/* Additional protection layers */
.ap-watermark::before {
    content: '' !important;
    position: absolute !important;
    top: -5px !important;
    left: -5px !important;
    right: -5px !important;
    bottom: -5px !important;
    background: transparent !important;
    pointer-events: none !important;
    z-index: -1 !important;
}

.ap-watermark::after {
    content: 'AutoPortfolio' !important;
    position: absolute !important;
    top: -1000px !important;
    left: -1000px !important;
    opacity: 0 !important;
    font-size: 0 !important;
}

/* Prevent common hiding attempts */
#ap-watermark[style*="display: none"],
#ap-watermark[style*="display:none"],
#ap-watermark[style*="visibility: hidden"],
#ap-watermark[style*="visibility:hidden"],
#ap-watermark[style*="opacity: 0"],
#ap-watermark[style*="opacity:0"] {
    display: block !important;
    visibility: visible !important;
    opacity: 1 !important;
}

/* Print protection */
@media print {
    .ap-watermark {
        display: block !important;
        position: fixed !important;
        bottom: 10px !important;
        right: 10px !important;
        background: black !important;
        color: white !important;
        padding: 5px 8px !important;
        font-size: 10px !important;
        border: 1px solid black !important;
    }
    
    .ap-watermark::before {
        content: 'Generated by AutoPortfolio - github.com/v-vekpawar/autoportfolio' !important;
        position: static !important;
        display: block !important;
        opacity: 1 !important;
        font-size: 10px !important;
    }
}

.footer-attribution {
    margin-top: 10px;
    text-align: center;
}

.ap-attribution {
    color: var(--text-muted);
    text-decoration: none;
    font-size: 14px;
    display: inline-flex;
    align-items: center;
    gap: 5px;
    transition: color 0.3s ease;
}

.ap-attribution:hover {
    color: var(--primary-color);
}

.ap-attribution i {
    color: var(--primary-color);
}

/* Header Styles */
.header {
    position: fixed;
    top: 0;
    width: 100%;
    background: rgba(255, 255, 255, 0.95);
    backdrop-filter: blur(10px);
    z-index: 1000;
    border-bottom: 1px solid rgba(0, 0, 0, 0.1);
}

.nav {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1rem 0;
}

.nav-brand {
    font-size: 1.5rem;
    font-weight: 700;
    color: var(--primary-color);
}

.nav-menu {
    display: flex;
    list-style: none;
    gap: 2rem;
}

.nav-menu a {
    text-decoration: none;
    color: var(--text-color);
    font-weight: 500;
    transition: color 0.3s ease;
}

.nav-menu a:hover {
    color: var(--primary-color);
}

/* Hero Section */
.hero {
    min-height: 100vh;
    display: flex;
    align-items: center;
    background: linear-gradient(135deg, var(--bg-color) 0%, var(--bg-secondary) 100%);
}

.hero-content {
    text-align: center;
    max-width: 800px;
    margin: 0 auto;
}

.hero-title {
    font-size: 3.5rem;
    font-weight: 700;
    margin-bottom: 1rem;
    background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
}

.hero-subtitle {
    font-size: 1.5rem;
    color: var(--text-muted);
    margin-bottom: 1.5rem;
}

.hero-description {
    font-size: 1.1rem;
    color: var(--text-color);
    margin-bottom: 2rem;
    line-height: 1.8;
}

.hero-buttons {
    display: flex;
    gap: 1rem;
    justify-content: center;
    flex-wrap: wrap;
}

/* Buttons */
.btn {
    display: inline-block;
    padding: 12px 24px;
    border-radius: 8px;
    text-decoration: none;
    font-weight: 500;
    transition: all 0.3s ease;
    border: none;
    cursor: pointer;
}

.btn-primary {
    background: var(--primary-color);
    color: white;
}

.btn-primary:hover {
    background: var(--primary-hover);
    transform: translateY(-2px);
}

.btn-secondary {
    background: transparent;
    color: var(--primary-color);
    border: 2px solid var(--primary-color);
}

.btn-secondary:hover {
    background: var(--primary-color);
    color: white;
}

.btn-sm {
    padding: 8px 16px;
    font-size: 0.9rem;
}

.btn-outline {
    background: transparent;
    border: 1px solid var(--border-color);
    color: var(--text-color);
}

.btn-outline:hover {
    background: var(--primary-color);
    color: white;
    border-color: var(--primary-color);
}

/* Sections */
.section {
    padding: 5rem 0;
}

.section-title {
    font-size: 2.5rem;
    font-weight: 700;
    text-align: center;
    margin-bottom: 3rem;
    color: var(--text-color);
}

/* Timeline */
.timeline {
    position: relative;
    max-width: 800px;
    margin: 0 auto;
}

.timeline::before {
    content: '';
    position: absolute;
    left: 50%;
    top: 0;
    bottom: 0;
    width: 2px;
    background: var(--primary-color);
    transform: translateX(-50%);
}

.timeline-item {
    position: relative;
    margin-bottom: 2rem;
}

.timeline-item:nth-child(odd) .timeline-content {
    margin-right: 50%;
    padding-right: 2rem;
    text-align: right;
}

.timeline-item:nth-child(even) .timeline-content {
    margin-left: 50%;
    padding-left: 2rem;
}

.timeline-content {
    background: var(--card-bg);
    padding: 1.5rem;
    border-radius: 8px;
    box-shadow: var(--shadow);
    position: relative;
}

.timeline-content h3 {
    color: var(--primary-color);
    margin-bottom: 0.5rem;
}

.timeline-content h4 {
    color: var(--text-muted);
    margin-bottom: 0.5rem;
}

.timeline-date {
    color: var(--text-muted);
    font-size: 0.9rem;
    font-weight: 500;
}

/* Projects Grid */
.projects-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 2rem;
    margin-top: 2rem;
}

.project-card {
    background: var(--card-bg);
    padding: 2rem;
    border-radius: 12px;
    box-shadow: var(--shadow);
    transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.project-card:hover {
    transform: translateY(-5px);
    box-shadow: var(--shadow-hover);
}

.project-card h3 {
    color: var(--primary-color);
    margin-bottom: 1rem;
}

.project-tech {
    margin: 1rem 0;
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
}

.tech-tag {
    background: var(--primary-color);
    color: white;
    padding: 4px 8px;
    border-radius: 4px;
    font-size: 0.8rem;
}

.project-links {
    margin-top: 1rem;
    display: flex;
    gap: 1rem;
}

.project-stats {
    margin-top: 1rem;
    color: var(--text-muted);
}

/* Skills Grid */
.skills-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: 1rem;
    margin-top: 2rem;
}

.skill-item {
    background: var(--card-bg);
    padding: 1rem;
    border-radius: 8px;
    text-align: center;
    box-shadow: var(--shadow);
    transition: transform 0.3s ease;
}

.skill-item:hover {
    transform: translateY(-3px);
}

/* Education & Certificates */
.education-list, .certificates-grid {
    display: grid;
    gap: 1.5rem;
    margin-top: 2rem;
}

.certificates-grid {
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
}

.education-item, .certificate-item {
    background: var(--card-bg);
    padding: 1.5rem;
    border-radius: 8px;
    box-shadow: var(--shadow);
}

.education-item h3, .certificate-item h3 {
    color: var(--primary-color);
    margin-bottom: 0.5rem;
}

.education-year, .cert-date {
    color: var(--text-muted);
    font-size: 0.9rem;
}

/* Contact */
.contact-content {
    text-align: center;
    max-width: 600px;
    margin: 0 auto;
}

.contact-info {
    display: flex;
    justify-content: center;
    gap: 2rem;
    margin-top: 2rem;
    flex-wrap: wrap;
}

.contact-link {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    color: var(--primary-color);
    text-decoration: none;
    font-weight: 500;
}

.contact-link:hover {
    color: var(--primary-hover);
}

/* Footer */
.footer {
    background: var(--bg-secondary);
    padding: 2rem 0;
    text-align: center;
    border-top: 1px solid var(--border-color);
}

/* Responsive Design */
@media (max-width: 768px) {
    .hero-title {
        font-size: 2.5rem;
    }
    
    .nav-menu {
        display: none;
    }
    
    .timeline::before {
        left: 20px;
    }
    
    .timeline-item:nth-child(odd) .timeline-content,
    .timeline-item:nth-child(even) .timeline-content {
        margin-left: 40px;
        margin-right: 0;
        padding-left: 1rem;
        padding-right: 1rem;
        text-align: left;
    }
    
    .hero-buttons {
        flex-direction: column;
        align-items: center;
    }
    
    .contact-info {
        flex-direction: column;
        gap: 1rem;
    }
}
"""

        # Theme-specific variables
        theme_vars = {
            'modern': """
/* Modern Theme Variables */
:root {
    --primary-color: #6366f1;
    --primary-hover: #5855eb;
    --secondary-color: #8b5cf6;
    --bg-color: #0f172a;
    --bg-secondary: #1e293b;
    --text-color: #f1f5f9;
    --text-muted: #94a3b8;
    --card-bg: #1e293b;
    --border-color: #334155;
    --shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.3);
    --shadow-hover: 0 20px 25px -5px rgba(0, 0, 0, 0.4);
}

.modern-theme .header {
    background: rgba(15, 23, 42, 0.95);
    border-bottom-color: rgba(255, 255, 255, 0.1);
}
""",
            'minimal': """
/* Minimal Theme Variables */
:root {
    --primary-color: #2563eb;
    --primary-hover: #1d4ed8;
    --secondary-color: #3b82f6;
    --bg-color: #ffffff;
    --bg-secondary: #f8fafc;
    --text-color: #1e293b;
    --text-muted: #64748b;
    --card-bg: #ffffff;
    --border-color: #e2e8f0;
    --shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
    --shadow-hover: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
}
""",
            'professional': """
/* Professional Theme Variables */
:root {
    --primary-color: #059669;
    --primary-hover: #047857;
    --secondary-color: #10b981;
    --bg-color: #f9fafb;
    --bg-secondary: #ffffff;
    --text-color: #111827;
    --text-muted: #6b7280;
    --card-bg: #ffffff;
    --border-color: #d1d5db;
    --shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
    --shadow-hover: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
}
"""
        }
        
        return theme_vars.get(template_name, theme_vars['modern']) + base_css
    
    def _generate_js(self):
        """Generate JavaScript with watermark protection"""
        return """
// AutoPortfolio Generated JavaScript
// DO NOT REMOVE - Generated by AutoPortfolio
// License: Custom Proprietary License - Attribution Required

document.addEventListener('DOMContentLoaded', function() {
    // Smooth scrolling for navigation links
    const navLinks = document.querySelectorAll('a[href^="#"]');
    navLinks.forEach(link => {
        link.addEventListener('click', function(e) {
            e.preventDefault();
            const targetId = this.getAttribute('href');
            const targetSection = document.querySelector(targetId);
            if (targetSection) {
                targetSection.scrollIntoView({
                    behavior: 'smooth',
                    block: 'start'
                });
            }
        });
    });

    // AutoPortfolio Protection System (DO NOT REMOVE)
    const AP_SIGNATURE = 'autoportfolio_' + Date.now();
    
    function createWatermark() {
        const watermark = document.createElement('div');
        watermark.id = 'ap-watermark';
        watermark.className = 'ap-watermark';
        watermark.setAttribute('data-ap-protected', 'true');
        watermark.innerHTML = '<a href="https://github.com/v-vekpawar/autoportfolio" target="_blank" rel="noopener"><i class="fas fa-robot"></i> Built with AutoPortfolio</a>';
        return watermark;
    }

    function protectWatermark() {
        let watermark = document.getElementById('ap-watermark');
        if (!watermark) {
            watermark = createWatermark();
            document.body.appendChild(watermark);
        }
        
        // Multiple protection layers
        const protectionMethods = [
            // Method 1: MutationObserver
            function() {
                const observer = new MutationObserver(function(mutations) {
                    mutations.forEach(function(mutation) {
                        if (mutation.type === 'childList') {
                            mutation.removedNodes.forEach(function(node) {
                                if (node.id === 'ap-watermark' || node.getAttribute?.('data-ap-protected')) {
                                    setTimeout(protectWatermark, 100);
                                }
                            });
                        }
                        if (mutation.type === 'attributes' && mutation.target.id === 'ap-watermark') {
                            if (mutation.target.style.display === 'none' || 
                                mutation.target.style.visibility === 'hidden' ||
                                mutation.target.style.opacity === '0') {
                                mutation.target.style.display = 'block';
                                mutation.target.style.visibility = 'visible';
                                mutation.target.style.opacity = '1';
                            }
                        }
                    });
                });
                
                observer.observe(document.body, {
                    childList: true,
                    subtree: true,
                    attributes: true,
                    attributeFilter: ['style', 'class']
                });
            },
            
            // Method 2: Periodic check
            function() {
                setInterval(function() {
                    const wm = document.getElementById('ap-watermark');
                    if (!wm || wm.style.display === 'none' || !wm.parentNode) {
                        protectWatermark();
                    }
                }, 2000);
            },
            
            // Method 3: Event listeners
            function() {
                document.addEventListener('keydown', function(e) {
                    // Detect common developer tools shortcuts
                    if ((e.ctrlKey || e.metaKey) && (e.key === 'i' || e.key === 'j' || e.key === 'u')) {
                        setTimeout(protectWatermark, 500);
                    }
                });
            }
        ];
        
        protectionMethods.forEach(method => method());
    }

    // Initialize protection
    protectWatermark();

    // Animate elements on scroll
    const observerOptions = {
        threshold: 0.1,
        rootMargin: '0px 0px -50px 0px'
    };

    const scrollObserver = new IntersectionObserver(function(entries) {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.style.opacity = '1';
                entry.target.style.transform = 'translateY(0)';
            }
        });
    }, observerOptions);

    // Observe elements for animation
    const animateElements = document.querySelectorAll('.timeline-item, .project-card, .skill-item, .education-item, .certificate-item');
    animateElements.forEach(el => {
        el.style.opacity = '0';
        el.style.transform = 'translateY(20px)';
        el.style.transition = 'opacity 0.6s ease, transform 0.6s ease';
        scrollObserver.observe(el);
    });

    // Console messages (DO NOT REMOVE)
    console.log('%c🤖 This portfolio was generated by AutoPortfolio', 'color: #6366f1; font-size: 16px; font-weight: bold;');
    console.log('%cLearn more: https://github.com/v-vekpawar/autoportfolio', 'color: #8b5cf6; font-size: 14px;');
    console.log('%c⚠️  Removing AutoPortfolio attribution violates the license terms', 'color: #ef4444; font-size: 12px;');
    
    // License reminder
    Object.defineProperty(window, 'autoPortfolioLicense', {
        value: 'Custom Proprietary License - Attribution Required',
        writable: false,
        configurable: false
    });
});

// Anti-tampering measures
(function() {
    'use strict';
    
    // Prevent common watermark removal attempts
    const originalRemove = Element.prototype.remove;
    Element.prototype.remove = function() {
        if (this.id === 'ap-watermark' || this.getAttribute('data-ap-protected')) {
            console.warn('AutoPortfolio: Attribution removal is not permitted under the license terms.');
            return;
        }
        return originalRemove.call(this);
    };
    
    const originalRemoveChild = Node.prototype.removeChild;
    Node.prototype.removeChild = function(child) {
        if (child.id === 'ap-watermark' || child.getAttribute?.('data-ap-protected')) {
            console.warn('AutoPortfolio: Attribution removal is not permitted under the license terms.');
            return child;
        }
        return originalRemoveChild.call(this, child);
    };
    
    // Protect against style manipulation
    const originalSetAttribute = Element.prototype.setAttribute;
    Element.prototype.setAttribute = function(name, value) {
        if ((this.id === 'ap-watermark' || this.getAttribute('data-ap-protected')) && name === 'style') {
            if (value.includes('display:none') || value.includes('visibility:hidden') || value.includes('opacity:0')) {
                console.warn('AutoPortfolio: Hiding attribution is not permitted under the license terms.');
                return;
            }
        }
        return originalSetAttribute.call(this, name, value);
    };
})();
"""
    
    def _generate_readme(self, portfolio_data):
        """Generate README file for the portfolio"""
        return f"""# {portfolio_data.get('name', 'Portfolio')} - Personal Portfolio

This portfolio was automatically generated using **AutoPortfolio** - an intelligent portfolio generator.

## 🚀 About This Portfolio

- **Generated by**: [AutoPortfolio](https://github.com/v-vekpawar/autoportfolio)
- **Generated on**: {datetime.now().strftime('%B %d, %Y')}
- **Owner**: {portfolio_data.get('name', 'Portfolio Owner')}

## 📁 Files Included

- `index.html` - Main portfolio webpage
- `styles.css` - Styling and theme
- `script.js` - Interactive functionality
- `README.md` - This file

## 🌐 How to Use

1. **Local Viewing**: Open `index.html` in any web browser
2. **Web Hosting**: Upload all files to your web hosting service
3. **GitHub Pages**: Push to a GitHub repository and enable GitHub Pages

## 🎨 Customization

While this portfolio was automatically generated, you can customize:
- Colors and fonts in `styles.css`
- Content in `index.html`
- Interactive features in `script.js`

**Note**: Please keep the AutoPortfolio attribution as required by the license.

## 📄 License & Attribution

This portfolio was generated using AutoPortfolio. Please maintain the attribution links as required.

- **AutoPortfolio**: https://github.com/v-vekpawar/autoportfolio
- **License**: Custom Proprietary License
- **Attribution Required**: Yes

## 🤝 Support

For questions about AutoPortfolio or this generated portfolio:
- GitHub Issues: https://github.com/v-vekpawar/autoportfolio/issues
- Email: contact.vivekpawar@gmail.com

---

**Generated with ❤️ by AutoPortfolio**
"""
    
    def _generate_attribution_notice(self, portfolio_data):
        """Generate attribution notice file"""
        notice_template_path = os.path.join(os.path.dirname(__file__), 'ATTRIBUTION_NOTICE.txt')
        
        try:
            with open(notice_template_path, 'r', encoding='utf-8') as f:
                template_content = f.read()
        except FileNotFoundError:
            # Fallback content if template file doesn't exist
            template_content = """AUTOPORTFOLIO ATTRIBUTION NOTICE
================================

This portfolio was generated using AutoPortfolio - Intelligent Automated Portfolio Generator

🤖 AutoPortfolio Information:
- Repository: https://github.com/v-vekpawar/autoportfolio
- License: Custom Proprietary License
- Author: Vivek Pawar (contact.vivekpawar@gmail.com)

Generated on: {generation_date}
Portfolio Owner: {portfolio_owner}

⚖️ ATTRIBUTION REQUIRED - DO NOT REMOVE
"""
        
        return template_content.format(
            generation_date=datetime.now().strftime('%B %d, %Y at %I:%M %p'),
            portfolio_owner=portfolio_data.get('name', 'Unknown')
        )