services:
  - type: web
    name: autoportfolio-backend
    env: python
    buildCommand: pip install -r requirements.txt && playwright install
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: LINKEDIN_HEADLESS
        value: true
      - key: PORT
        value: 5001
    plan: free
    region: oregon
    branch: main
    rootDir: backend
