'use client';

import React, { useEffect } from 'react';
import { ExternalLink } from 'lucide-react';

interface AutoPortfolioWatermarkProps {
  className?: string;
  variant?: 'floating' | 'footer';
}

export default function AutoPortfolioWatermark({ 
  className = '', 
  variant = 'floating' 
}: AutoPortfolioWatermarkProps) {
  
  useEffect(() => {
    // Protect watermark from removal (basic protection)
    const protectWatermark = () => {
      const watermarks = document.querySelectorAll('[data-autoportfolio-watermark]');
      if (watermarks.length === 0) {
        console.warn('AutoPortfolio watermark removed - this violates the license terms');
      }
    };

    // Check periodically
    const interval = setInterval(protectWatermark, 5000);
    
    // Console attribution
    console.log(
      '%c🤖 This portfolio was generated by AutoPortfolio',
      'color: #6366f1; font-size: 16px; font-weight: bold; text-shadow: 1px 1px 2px rgba(0,0,0,0.1);'
    );
    console.log(
      '%cLearn more: https://github.com/v-vekpawar/autoportfolio',
      'color: #8b5cf6; font-size: 14px;'
    );

    return () => clearInterval(interval);
  }, []);

  const baseClasses = "autoportfolio-watermark transition-all duration-300 hover:scale-105";
  
  const variantClasses = {
    floating: `
      fixed bottom-4 right-4 z-50 
      bg-black/80 backdrop-blur-sm 
      text-white text-xs 
      px-3 py-2 rounded-full 
      border border-white/20
      shadow-lg hover:shadow-xl
      hover:bg-black/90
    `,
    footer: `
      inline-flex items-center gap-2 
      text-sm text-gray-500 
      hover:text-gray-700
    `
  };

  return (
    <div 
      className={`${baseClasses} ${variantClasses[variant]} ${className}`}
      data-autoportfolio-watermark="true"
      data-generator="AutoPortfolio"
    >
      <a
        href="https://github.com/v-vekpawar/autoportfolio"
        target="_blank"
        rel="noopener noreferrer"
        className="flex items-center gap-2 no-underline text-inherit hover:text-inherit"
        onClick={(e) => {
          // Track click for analytics (if needed)
          console.log('AutoPortfolio watermark clicked');
        }}
      >
        <span className="text-blue-400">🤖</span>
        <span className="font-medium">Built with AutoPortfolio</span>
        {variant === 'footer' && <ExternalLink className="w-3 h-3" />}
      </a>
    </div>
  );
}

// CSS to be injected (for additional protection)
export const watermarkCSS = `
/* AutoPortfolio Watermark Protection */
.autoportfolio-watermark {
  pointer-events: auto !important;
  user-select: none;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
}

.autoportfolio-watermark::before {
  content: '';
  position: absolute;
  top: -2px;
  left: -2px;
  right: -2px;
  bottom: -2px;
  background: transparent;
  pointer-events: none;
  z-index: -1;
}

/* Prevent easy hiding */
[data-autoportfolio-watermark] {
  display: block !important;
  visibility: visible !important;
  opacity: 1 !important;
}

/* Console warning for tampering attempts */
@media print {
  .autoportfolio-watermark {
    display: block !important;
  }
}
`;